name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: "⬆️ Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
version-resolver:
  default: minor
  major:
    labels:
      - 'version/major'
  minor:
    labels:
      - 'version/minor'
  patch:
    labels:
      - 'version/patch'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
template: |
  ## What's Changed

  $CHANGES
