name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'Breaking changes'
    labels:
      - 'breaking change'
  - title: 'Notable changes'
    labels:
      - 'version: major'
      - 'version: minor'
  - title: 'Dependencies'
    collapse-after: 1
    labels:
      - 'dependencies'
exclude-labels:
  - 'ci'
  - 'documentation'
  - 'repository'
  - 'testing'
version-resolver:
  default: patch
  major:
    labels:
      - 'breaking change'
      - 'version: major'
  minor:
    labels:
      - 'refactor'
      - 'enhancement'
      - 'version: minor'
  patch:
    labels:
      - 'bugfix'
      - 'dependencies'
      - 'version: patch'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
template: |
  ## What's Changed

  $CHANGES
